version: 2.1

jobs:
  build:
    shell: "/bin/bash -eol pipefail"
    docker:
      - image: "circleci/python"
    steps:
        - checkout
        - run: echo hello
        - run: sudo pip install selenium
        - run: |
            sudo apt-get install -y libglib2.0-0=2.50.3-2 \
            libnss3=2:3.26.2-1.1+deb9u1 \
            libgconf-2-4=3.2.6-4+b1 \
            libfontconfig1=2.11.0-6.7+b1

        - run: |
              curl --silent --show-error --location --fail --retry 3 --output /tmp/google-chrome-stable_current_amd64.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
              && (sudo dpkg -i /tmp/google-chrome-stable_current_amd64.deb || sudo apt-get -fy install)  \
              && rm -rf /tmp/google-chrome-stable_current_amd64.deb \
              && sudo sed -i 's|HERE/chrome"|HERE/chrome" --disable-setuid-sandbox --no-sandbox|g' \
              "/opt/google/chrome/google-chrome" \
               && google-chrome --version
        - run: |
              wget https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
              unzip chromedriver_linux64.zip
              sudo mv chromedriver /usr/bin/chromedriver
              sudo chown root:root /usr/bin/chromedriver
              sudo chmod +x /usr/bin/chromedriver
        - run: python test.py