version: '2.1'

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      - run: test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
      - run: test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
      - run: test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >> $BASH_ENV
      - run: echo "eval \$($(brew --prefix)/bin/brew shellenv)" >> $BASH_ENV
