version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - run: date +%F > date
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # cache should skip
            - date-cache-{{ checksum "date" }}
      - save_cache:
            key: date-cache-{{ checksum "date" }}
            paths:
                - "/test"