version: 2.1
executors:
  my-exec:
    docker:
      - image: cimg/base:stable
    resource_class: large

jobs:
  build:
    executor: my-exec
    steps:
      - run: echo "hello"
workflows:
  build_and_notify:
    jobs:
      - build
