version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          sudo apt-get update
          sudo apt-get upgrade
      - run: docker build


  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "test"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build