version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    macos:
      xcode: '11.4'
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - checkout

      - run:
          name: Setup dependencies
          command: brew install unixodbc gnupg coreutils mmv

      - node/install:
          install-yarn: true
          node-version: "12.13.1"
