version: 2
jobs:
  build:
    docker:
      - image: circleci/node

    steps:
      - run:
          name: hello
          command: |
            curl -v https://releases.hashicorp.com \
            apt-get install traceroute \
            traceroute https://releases.hashicorp.com
