version: 2.1
orbs:
  cypress: cypress-io/cypress@1.4.0
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          parallel: true
          parallelism: 3
          start: 'npm start:staging'
          wait-on: 'http://localhost:3001'