version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: |
            echo ${TEST}
            echo ${TEST2}
          environment:
            TEST2: "test2"
            TEST: '{"hello": true, "greeting": "welcome"}'
