version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: echo $TEST
          environment:
            TEST: '{"hello": true, "greeting": "welcome"}'
