version: 2 # use CircleCI 2.0
jobs: # a collection of steps

  build:
    machine: true
    steps:
      - run:
          name: echo test context
          command: echo "A non-existing context was attached"
