version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: |
          mkdir echo-output
          cd echo-output
          curl -vo myfile "ftp://speedtest:speedtest@ftp.otenet.gr/test5Gb-a.db"
      - persist_to_workspace:
          root: echo-output
          paths:
            - myfile

  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "test"
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build