version: 2
jobs:
  build:
    docker:
      - image: circleci/node
      - image: microsoft/mssql-server-linux
        environment:
          POSTGRES_USER: 'conductor'
          POSTGRES_DB: 'conductor_test'
    steps:
      - run:
          name: install dockerize
          command: |
            sudo wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
            sudo rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: 'v0.6.0'
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:1433 -timeout 1m
