version: 2
jobs:
  build:
    docker:
      - image: circleci/node
      - image: rabbitmq:3.6
      - image: circleci/mysql
    steps:
      - checkout
      - run: echo "build"
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test