version: 2

executors:
  common_executor:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: coverwallet
      - image: circleci/mongo:3.2-ram
    working_directory: ~/coverwallet/my-coverwallet
    shell: /bin/bash --login

jobs:
  build:
    executor: common_executor
    steps:
      - run: echo "hello world"