version: 2 # use CircleCI 2.0
jobs: # a collection of steps

  deploy:
    docker:
      - image: circleci/python:2.7
    steps:
      - run:
          name: echo test context
          command: "A non-existing context was attached"

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file
          when: on_fail
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - deploy:
          context: org-oneTest