version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: sleep 30
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: sleep 20
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: sleep 10
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          type: approval
          requires: 
            - build
      - deploy:
          requires: 
            - test