version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo test 2
      - run:
          command: |
            echo Running test
  hold:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo test 2
      - run:
          command: |
            echo Running hold
workflows:
  test:
    jobs:
      - hold
      - build

