version: 2.1
jobs:
  build:
    parameters:
      object:
        default: '{"hello": true, "greeting": "welcome"}'
        type: string
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: |
            TESTME="2"
            echo "export TESTME=${TESTME} >> $BASH_ENV"
            cat $BASH_ENV
      - run: echo $TESTME

