version: 2.1
setup: false
executors:
  my-executor:
    docker:
    - image: cimg/base:stable
    resource_class: medium
jobs:
  flow:
    executor:
      name: my-executor
    steps:
    - persist_to_workspace:
        root: workspace
        paths:
        - echo-output
  downstream:
    executor:
      name: my-executor
    steps:
    - attach_workspace:
        at: "/tmp/workspace"
workflows:
  btd:
    jobs:
    - flow: {}
    - downstream:
        requires:
        - flow