version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.2.7-fpm
    working_directory: /dev/shm
    steps:
    - checkout
    - run: |
        pwd
        ls
    - run: npm install --verbose
