version: 2.1
orbs:
  github-cli: circleci/github-cli@dev:alpha
workflows:
  build_and_notify:
    jobs:
      - github-cli/release:
          tag: "1.0.0"
          title: "A test release"
          context: GITHUB
