version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: |
          traceroute https://gcr.io


  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "test"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build