version: 2.1
orbs:
  github-cli: circleci/github-cli@dev:alpha
workflows:
  build_and_notify:
    jobs:
      - github-cli/release:
          tag: "2.0.0"
          title: "Version 2: A Major Change"
          notes-file: "./changelog.md"
          context: GITHUB
