version: 2.1

orbs:
  node: circleci/node@4.1.1

jobs:
  build-macos:
    macos:
      xcode: '11.4'
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - checkout

      - run:
          name: Setup dependencies
          command: brew install unixodbc gnupg coreutils

      - node/install:
          install-yarn: true
          node-version: "12.13.1"

workflows:
  version: 2
  build:
    jobs:
      - build