version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: date > date
      - save_cache:
            key: date-cache-{{ checksum "date" }}
            paths:
                - "/test"