version: 2.1
jobs:
  build:
      macos:
        xcode: 9.0.0
      steps:
          - run: echo "hello world"
  linux:
      docker:
        - image: circleci/node
      steps:
          - run: echo "hello world"
workflows:
  thisone:
    jobs:
      - build
      - linux