version: 2.1

jobs:
  test1:
    docker:
      - image: us-docker.pkg.dev/stackpulse/public/cli:latest
    steps:
      - run: echo hello
  test2:
    docker:
      - image: us-docker.pkg.dev/stackpulse/public/cli:latest
        entrypoint: "top"
    steps:
      - run: echo hello
  test3:
    docker:
      - image: us-docker.pkg.dev/stackpulse/public/cli:latest
        entrypoint: ""
    steps:
      - run: echo hello
workflows:
  myWorkflow:
    jobs:
      - test1
      - test2
      - test3