version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo test 2
      - run:
          command: |
            echo Running test
            set +e
            mkdir -p /tmp/test-results
            make test

      - run:
          shell: /bin/sh
          command: |
            echo Running test
            mkdir -p /tmp/test-results
            make test