version: 2.1

jobs:
  build:
    docker:
      - image: node
    steps:
      - run:
          command:
            while [ true ]
            do
              sleep 10
              echo date 1>&2
            done