version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10-stretch-browsers
    environment:
      NODE_ENV: 'production'
      BUILD_DIR: ~/cb-build/dist
    steps:
    - checkout
    - run: npm install --verbose
    - run: |
        yarn lint
        yarn build