version: 2.1
orbs:
  slack: circleci/slack@4.4
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo Hello
      - slack/notify:
          channel: ABCXYZ
          event: pass
          template: basic_success_1
workflows:
  build_and_notify:
    jobs:
      - build:
          context:
            - SLACK