version: 2
jobs:
  build:
    docker:
      - image: circleci/node
#   This is a test
    steps:
      - checkout
      - run:
         name: Install tunnel to CrossBrowserTesting
         command: npm install -g cbt_tunnels; TUNNEL_NAME="test"