version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "workflow1"
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "workflow2"
workflows:
  version: 2
  wf1:
    jobs:
      - build
  wf2:
    jobs:
      - test
