version: 2.1
jobs:
  build:
    parameters:
      object:
        default: '{"hello": true, "greeting": "welcome"}'
        type: string
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: |
            echo ${TEST}
            echo ${TEST2}
          environment:
            TEST2: "test2"
            TEST: '<<parameters.object>>'
