version: 2
jobs:
  build:
    machine: true

    steps:
      - run:
          name: Prepare Environment
          shell: sudo /bin/bash -eo pipefail
          command: |
              echo "Update ulimit"
              ulimit -n 65535
              echo "Update max watchers"
              sysctl fs.inotify.max_user_watches=1048576 | tee -a /etc/sysctl.conf # increases the number of watches for telemetry watcher tests