version: 2
jobs:
  build:
    docker:
      - image: circleci/node
#   This is a test
    steps:
      - checkout
      - run:
         name: Install VueCLI as Global with sudo
         command: sudo npm install -g @vue/cli
      - run:
         name: Install tunnel to CrossBrowserTesting
         command: sudo npm install -g cbt_tunnels; TUNNEL_NAME="test"