version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/ruby:2.5.0-node-browsers"
    steps:
        - checkout
        - run: which chromedriver
        - run: chromedriver --version
        - run: |
              wget https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
              unzip chromedriver_linux64.zip
              sudo mv chromedriver /usr/local/bin/chromedriver
              sudo chown root:root /usr/local/bin/chromedriver
              sudo chmod +x /usr/local/bin/chromedriver

        - run: chromedriver --version