version: 2.1

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: |
          if [ 1 = 1 ]; then
            if [ 2 = 2 ]; then
              echo hello
            fi
          fi
