version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/node"
    steps:
        - run: echo hello
        - run: |
              wget https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
              unzip chromedriver_linux64.zip
              sudo mv chromedriver /usr/bin/chromedriver
              sudo chown root:root /usr/bin/chromedriver
              sudo chmod +x /usr/bin/chromedriver
        - run:
              name: Execute Chrome in Background
              command: chromedriver --url-base=/wd/hub
              background: true