version: 2.1
executors:
    node8:
        docker:
            - image: circleci/node:8

commands:
    callhello:
        steps:
            - run:
                name: Call HelloWorld
                command: echo hello

jobs:
    build:
        executor: node8
        working_directory: ~/repo

        steps:
            - callhello

    hello:
        executor: node8
        working_directory: ~/repo

        steps:
            - run:
                name: HelloWorld
                command: echo "HelloWorld"

workflows:
    version: 2
    build:
        jobs:
            - build
    hello:
        jobs:
            - hello