version: 2.1
jobs:
  build:
    parameters:
      object:
        default: '{"hello": true, "greeting": "welcome"}'
        type: string
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          environment:
            TESTME: ${!HOME}
          command: echo $TESTME


