version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.2.7-fpm
    working_directory: /dev/shm
    resource_class: medium+
    steps:
    - checkout
    - run: |
        pwd
        ls
    - run: |
        touch testfile
        ls
    - run: dmesg -H
