version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: test 1
          command: |
            cd ../
            pwd
      - run:
          name: test 2
          environment:
            PARAM_LOC: "../"
          command: |
            cd "$PARAM_LOC"
            pwd
      - run:
          name: test 3
          command: |
            cat ./README.md
      - run:
          name: test 4
          environment:
            PARAM_RM: "./README.md"
          command: |
            echo "$PARAM_RM"
            cat $PARAM_RM
      - run:
          name: test 5
          environment:
            PARAM_RM: "./README.md"
          command: |
            echo "$PARAM_RM"
            cat "$PARAM_RM"
workflows:
  version: 2
  build:
    jobs:
      - build