version: 2
jobs:
  build:
    docker:
      - image: circleci/node
      - image: circleci/postgres
    steps:
      - run:
          command: sudo -u postgres psql -p 5432 -c "create user ubuntu with password '';"
          command: sudo -u postgres psql -p 5432 -c "alter user ubuntu with superuser;"
