version: 2.1
# test
jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run:
          no_output_timeout: 1m
          DebugFilename: ~/debugfile.txt
          command: |
            chmod +x runthis.sh
            ./runthis.sh
      - store_artifacts:
          path: ~/