version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.2.7-fpm
    working_directory: /dev/shm
    resource_class: medium+
    steps:
    - checkout
    - run: cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes
