version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: |
          curl "http://www.office.xerox.com/latest/SFTBR-04U.PDF" > ~/echo-output/myfile
      - persist_to_workspace:
          root: /
          paths:
            - echo-output

  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "test"
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test