version: 2

jobs:
  build:
    docker:
      - image: wearejh/ci-build-env:deploys
        environment:
          MYSQL_TEST_HOST: 127.0.0.1
          MYSQL_TEST_DATABASE: circle_test
          MYSQL_TEST_USER: root
          MYSQL_TEST_PASSWORD: root
      - image: circleci/mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: root

    working_directory: /root/build

    steps:
      - checkout
      - run: echo "PASS 1"


      # Restore Composer Cache
      - restore_cache:
          keys:
            - jml-composer-{{ checksum "composer.lock" }}
            - jml-composer-

      # Restore Yarn Cache
      - restore_cache:
          keys:
            - jml-yarn-{{ checksum "yarn.lock" }}
            - jml-yarn-

      # Dependencies
      - run: composer install
      - run: yarn && yarn run build-all

      # Save Composer Cache
      - save_cache:
          key: jml-composer-{{ checksum "composer.lock" }}
          paths:
            - ~/.composer/cache

      # Save Yarn Cache
      - save_cache:
          key: jml-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: echo "PASS 2"

  deploy:
    docker:
      - image: wearejh/ci-build-env:deploys

    working_directory: /root/build

    steps:
      # Restore Build
      - restore_cache:
        key: jml-build-{{ .Revision }}

      # Deploy
      - deploy:
          command: |
            [[ -n "$CIRLCE_PULL_REQUEST" ]] && exit 0
            if [ "${CIRCLE_BRANCH}" = "develop" ]; then
                knock $HOST 123 234 345; dep ssh:preconnect dev -vvv
                dep deploy dev -vvv
                dep release:upgrade dev -vvv
            fi
            if echo ${CIRCLE_BRANCH} | grep 'release-.*'; then
                echo "Deploy staging..."
            fi