version: 2
jobs:
  build:
    docker:
      - image: circleci/node

    steps:
      - run:
          name: hello
          command: |
            curl --silent --fail https://releases.hashicorp.com/packer/0.12.1/packer_0.12.1_linux_amd64.zip -o packer.zip 
