version: 2
jobs:
  build:
    docker:
      - image: circleci/node
#   This is a test 1
    steps:
      - add_ssh_keys:
        fingerprints:
          - "b7:35:a6:4e:9b:0d:6d:d4:78:1e:9a:97:2a:66:6b:be"
      - run: echo "Success"