version: 2.1

jobs:
  build:
    shell: "/bin/bash -eol pipefail"
    docker:
      - image: "circleci/python"
    steps:
        - checkout
        - run: echo hello
        - run: pip install selenium
        - run: |
              wget https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
              unzip chromedriver_linux64.zip
              sudo mv chromedriver /usr/bin/chromedriver
              sudo chown root:root /usr/bin/chromedriver
              sudo chmod +x /usr/bin/chromedriver
        - run: python test.py